# Generated by Django 4.2.11 on 2026-04-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='attendance__user_id_e2bd98_idx',
            old_name='attendance__user_id_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='attendance__organiz_32a300_idx',
            old_name='attendance__org_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='attendance__is_late_263f82_idx',
            old_name='attendance__is_late_idx',
        ),
        migrations.RenameIndex(
            model_name='checkinevent',
            new_name='attendance__user_id_621079_idx',
            old_name='attendance__event_user_idx',
        ),
        migrations.RenameIndex(
            model_name='checkinevent',
            new_name='attendance__attenda_cf1d42_idx',
            old_name='attendance__event_rec_idx',
        ),
    ]
