# Generated by Django 4.2.11 on 2026-04-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geofencing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='locationupdate',
            new_name='geofencing__user_id_e6a9d8_idx',
            old_name='geofencing__user_id_3c4f2b_idx',
        ),
        migrations.RenameIndex(
            model_name='locationupdate',
            new_name='geofencing__geofenc_543b1c_idx',
            old_name='geofencing__geofence_3c4f2b_idx',
        ),
    ]
